// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/p2p/dht/dht.proto

package dht

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerkleNode_Type int32

const (
	MerkleNode_FILE_CHUNK MerkleNode_Type = 0
	MerkleNode_META_LINK  MerkleNode_Type = 1
)

// Enum value maps for MerkleNode_Type.
var (
	MerkleNode_Type_name = map[int32]string{
		0: "FILE_CHUNK",
		1: "META_LINK",
	}
	MerkleNode_Type_value = map[string]int32{
		"FILE_CHUNK": 0,
		"META_LINK":  1,
	}
)

func (x MerkleNode_Type) Enum() *MerkleNode_Type {
	p := new(MerkleNode_Type)
	*p = x
	return p
}

func (x MerkleNode_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerkleNode_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_p2p_dht_dht_proto_enumTypes[0].Descriptor()
}

func (MerkleNode_Type) Type() protoreflect.EnumType {
	return &file_internal_p2p_dht_dht_proto_enumTypes[0]
}

func (x MerkleNode_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerkleNode_Type.Descriptor instead.
func (MerkleNode_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_p2p_dht_dht_proto_rawDescGZIP(), []int{0, 0}
}

type MerkleNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MerkleNode_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=dht.MerkleNode_Type" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Links         [][]byte               `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleNode) Reset() {
	*x = MerkleNode{}
	mi := &file_internal_p2p_dht_dht_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleNode) ProtoMessage() {}

func (x *MerkleNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_dht_dht_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleNode.ProtoReflect.Descriptor instead.
func (*MerkleNode) Descriptor() ([]byte, []int) {
	return file_internal_p2p_dht_dht_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleNode) GetType() MerkleNode_Type {
	if x != nil {
		return x.Type
	}
	return MerkleNode_FILE_CHUNK
}

func (x *MerkleNode) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MerkleNode) GetLinks() [][]byte {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MerkleNode) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type KBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Peers         []*PeerStoreEntry      `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KBucket) Reset() {
	*x = KBucket{}
	mi := &file_internal_p2p_dht_dht_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KBucket) ProtoMessage() {}

func (x *KBucket) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_dht_dht_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KBucket.ProtoReflect.Descriptor instead.
func (*KBucket) Descriptor() ([]byte, []int) {
	return file_internal_p2p_dht_dht_proto_rawDescGZIP(), []int{1}
}

func (x *KBucket) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *KBucket) GetPeers() []*PeerStoreEntry {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerStoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	HashId        []byte                 `protobuf:"bytes,2,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	LastKnownAddr string                 `protobuf:"bytes,3,opt,name=last_known_addr,json=lastKnownAddr,proto3" json:"last_known_addr,omitempty"`
	LastSeen      uint64                 `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	TrustScore    uint32                 `protobuf:"varint,5,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStoreEntry) Reset() {
	*x = PeerStoreEntry{}
	mi := &file_internal_p2p_dht_dht_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStoreEntry) ProtoMessage() {}

func (x *PeerStoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_dht_dht_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStoreEntry.ProtoReflect.Descriptor instead.
func (*PeerStoreEntry) Descriptor() ([]byte, []int) {
	return file_internal_p2p_dht_dht_proto_rawDescGZIP(), []int{2}
}

func (x *PeerStoreEntry) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *PeerStoreEntry) GetHashId() []byte {
	if x != nil {
		return x.HashId
	}
	return nil
}

func (x *PeerStoreEntry) GetLastKnownAddr() string {
	if x != nil {
		return x.LastKnownAddr
	}
	return ""
}

func (x *PeerStoreEntry) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerStoreEntry) GetTrustScore() uint32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

var File_internal_p2p_dht_dht_proto protoreflect.FileDescriptor

const file_internal_p2p_dht_dht_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/p2p/dht/dht.proto\x12\x03dht\"\x9b\x01\n" +
	"\n" +
	"MerkleNode\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.dht.MerkleNode.TypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05links\x18\x03 \x03(\fR\x05links\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\"%\n" +
	"\x04Type\x12\x0e\n" +
	"\n" +
	"FILE_CHUNK\x10\x00\x12\r\n" +
	"\tMETA_LINK\x10\x01\"J\n" +
	"\aKBucket\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12)\n" +
	"\x05peers\x18\x02 \x03(\v2\x13.dht.PeerStoreEntryR\x05peers\"\xa8\x01\n" +
	"\x0ePeerStoreEntry\x12\x17\n" +
	"\apub_key\x18\x01 \x01(\fR\x06pubKey\x12\x17\n" +
	"\ahash_id\x18\x02 \x01(\fR\x06hashId\x12&\n" +
	"\x0flast_known_addr\x18\x03 \x01(\tR\rlastKnownAddr\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x04R\blastSeen\x12\x1f\n" +
	"\vtrust_score\x18\x05 \x01(\rR\n" +
	"trustScoreB=Z;github.com/DmytroBuzhylov/echofog-core/internal/p2p/dht;dhtb\x06proto3"

var (
	file_internal_p2p_dht_dht_proto_rawDescOnce sync.Once
	file_internal_p2p_dht_dht_proto_rawDescData []byte
)

func file_internal_p2p_dht_dht_proto_rawDescGZIP() []byte {
	file_internal_p2p_dht_dht_proto_rawDescOnce.Do(func() {
		file_internal_p2p_dht_dht_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_dht_dht_proto_rawDesc), len(file_internal_p2p_dht_dht_proto_rawDesc)))
	})
	return file_internal_p2p_dht_dht_proto_rawDescData
}

var file_internal_p2p_dht_dht_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_p2p_dht_dht_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_p2p_dht_dht_proto_goTypes = []any{
	(MerkleNode_Type)(0),   // 0: dht.MerkleNode.Type
	(*MerkleNode)(nil),     // 1: dht.MerkleNode
	(*KBucket)(nil),        // 2: dht.KBucket
	(*PeerStoreEntry)(nil), // 3: dht.PeerStoreEntry
}
var file_internal_p2p_dht_dht_proto_depIdxs = []int32{
	0, // 0: dht.MerkleNode.type:type_name -> dht.MerkleNode.Type
	3, // 1: dht.KBucket.peers:type_name -> dht.PeerStoreEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_p2p_dht_dht_proto_init() }
func file_internal_p2p_dht_dht_proto_init() {
	if File_internal_p2p_dht_dht_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_dht_dht_proto_rawDesc), len(file_internal_p2p_dht_dht_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_p2p_dht_dht_proto_goTypes,
		DependencyIndexes: file_internal_p2p_dht_dht_proto_depIdxs,
		EnumInfos:         file_internal_p2p_dht_dht_proto_enumTypes,
		MessageInfos:      file_internal_p2p_dht_dht_proto_msgTypes,
	}.Build()
	File_internal_p2p_dht_dht_proto = out.File
	file_internal_p2p_dht_dht_proto_goTypes = nil
	file_internal_p2p_dht_dht_proto_depIdxs = nil
}
